import type { Recipe, Subs } from "./types";

export const DEFAULT_RECIPES: Recipe[] = [
  { name: "Classic Omelet", time_minutes: 10, tags: ["vegetarian", "gluten-free", "quick", "breakfast"], cuisine: "French",
    ingredients: { eggs: 2, butter: 1, salt: 1, pepper: 1 },
    steps: ["Beat eggs with salt and pepper.", "Melt butter in pan.", "Pour eggs, cook 2 min, fold and serve."] },
  { name: "Garlic Fried Rice", time_minutes: 15, tags: ["vegetarian", "quick", "asian"], cuisine: "Asian",
    ingredients: { rice: 2, garlic: 3, "soy sauce": 1, oil: 1, onion: 1, eggs: 1 },
    steps: ["Heat oil, sauté garlic and onion.", "Add rice, stir-fry 3 min.", "Scramble egg in, mix in soy sauce."] },
  { name: "Tomato Pasta", time_minutes: 20, tags: ["vegetarian", "italian", "quick"], cuisine: "Italian",
    ingredients: { pasta: 200, tomato: 3, garlic: 2, oil: 1, salt: 1, basil: 1 },
    steps: ["Boil pasta.", "Sauté garlic in oil, add tomato.", "Toss pasta with sauce and basil."] },
  { name: "Chicken Stir-Fry", time_minutes: 25, tags: ["asian", "quick", "high-protein"], cuisine: "Asian",
    ingredients: { chicken: 300, "soy sauce": 2, garlic: 2, onion: 1, "bell pepper": 1, oil: 1, ginger: 1 },
    steps: ["Sear chicken in oil.", "Add aromatics and veg, stir-fry 5 min.", "Finish with soy sauce."] },
  { name: "Chickpea Curry", time_minutes: 30, tags: ["vegetarian", "vegan", "gluten-free", "indian"], cuisine: "Indian",
    ingredients: { chickpeas: 400, onion: 1, tomato: 2, garlic: 2, ginger: 1, "curry powder": 2, oil: 1, "coconut milk": 200 },
    steps: ["Sauté onion, garlic, ginger.", "Add spices, tomato, chickpeas.", "Simmer with coconut milk 15 min."] },
  { name: "Caesar Salad", time_minutes: 10, tags: ["quick", "salad"], cuisine: "American",
    ingredients: { lettuce: 1, parmesan: 1, croutons: 1, lemon: 1, garlic: 1, oil: 1, anchovy: 1 },
    steps: ["Whisk dressing.", "Toss lettuce, croutons, parmesan with dressing."] },
  { name: "Mushroom Risotto", time_minutes: 40, tags: ["vegetarian", "italian"], cuisine: "Italian",
    ingredients: { rice: 1, mushroom: 200, onion: 1, garlic: 2, butter: 2, parmesan: 1, "vegetable broth": 500 },
    steps: ["Sauté onion, garlic, mushrooms.", "Add rice, then broth ladle by ladle.", "Finish with butter and parmesan."] },
  { name: "Black Bean Tacos", time_minutes: 15, tags: ["vegetarian", "vegan", "mexican", "quick"], cuisine: "Mexican",
    ingredients: { "black beans": 400, tortilla: 4, onion: 1, garlic: 1, cumin: 1, lime: 1, cilantro: 1, oil: 1 },
    steps: ["Sauté onion, garlic, cumin.", "Add beans, mash slightly.", "Fill tortillas with lime and cilantro."] },
  { name: "Banana Pancakes", time_minutes: 20, tags: ["vegetarian", "breakfast"], cuisine: "American",
    ingredients: { banana: 2, eggs: 2, flour: 1, milk: 1, sugar: 1, butter: 1 },
    steps: ["Mash bananas, mix with eggs, flour, milk, sugar.", "Cook in butter until golden."] },
  { name: "Lentil Soup", time_minutes: 35, tags: ["vegetarian", "vegan", "gluten-free", "soup"], cuisine: "Mediterranean",
    ingredients: { lentils: 200, onion: 1, carrot: 2, celery: 2, garlic: 2, "vegetable broth": 700, cumin: 1, oil: 1 },
    steps: ["Sauté veg.", "Add lentils, broth, cumin.", "Simmer 25 min."] },
  { name: "Grilled Cheese", time_minutes: 8, tags: ["vegetarian", "quick"], cuisine: "American",
    ingredients: { bread: 2, cheddar: 1, butter: 1 },
    steps: ["Butter bread, fill with cheese.", "Grill until golden both sides."] },
  { name: "Shakshuka", time_minutes: 25, tags: ["vegetarian", "breakfast"], cuisine: "Middle Eastern",
    ingredients: { eggs: 3, tomato: 4, onion: 1, "bell pepper": 1, garlic: 2, cumin: 1, paprika: 1, oil: 1 },
    steps: ["Sauté onion, pepper, garlic.", "Add tomato and spices, simmer.", "Crack eggs in, cover, cook until set."] },
];

export const DEFAULT_SUBS: Subs = {
  butter: ["oil", "margarine", "ghee"],
  oil: ["butter", "ghee"],
  milk: ["yogurt", "cream", "almond milk", "oat milk"],
  yogurt: ["milk", "sour cream"],
  cream: ["milk", "yogurt"],
  lemon: ["lime", "vinegar"],
  lime: ["lemon"],
  "soy sauce": ["tamari", "fish sauce"],
  honey: ["sugar", "maple syrup"],
  sugar: ["honey", "maple syrup"],
  rice: ["quinoa", "couscous"],
  pasta: ["noodles"],
  noodles: ["pasta"],
  chicken: ["turkey", "tofu"],
  beef: ["pork", "lamb"],
  tofu: ["chicken", "paneer"],
  cilantro: ["parsley"],
  parsley: ["cilantro"],
  onion: ["shallot", "leek"],
  shallot: ["onion"],
  garlic: ["garlic powder"],
  tomato: ["canned tomato"],
  cheddar: ["mozzarella", "gouda"],
  mozzarella: ["cheddar"],
};

// Rough nutrition per *unit* used in the recipes above
// (a "unit" loosely maps to "1 of the thing" — 1 egg, 1 tbsp oil, 100g pasta etc.)
// This is intentionally heuristic — good enough for a demo.
export const NUTRITION: Record<string, { kcal: number; protein: number; carbs: number; fat: number }> = {
  eggs:        { kcal: 78,  protein: 6,   carbs: 0.6, fat: 5 },
  butter:      { kcal: 102, protein: 0.1, carbs: 0,   fat: 12 },
  oil:         { kcal: 120, protein: 0,   carbs: 0,   fat: 14 },
  salt:        { kcal: 0,   protein: 0,   carbs: 0,   fat: 0 },
  pepper:      { kcal: 6,   protein: 0.2, carbs: 1.5, fat: 0 },
  rice:        { kcal: 206, protein: 4,   carbs: 45,  fat: 0.4 },
  garlic:      { kcal: 4,   protein: 0.2, carbs: 1,   fat: 0 },
  "soy sauce": { kcal: 8,   protein: 1,   carbs: 0.8, fat: 0 },
  onion:       { kcal: 44,  protein: 1,   carbs: 10,  fat: 0 },
  pasta:       { kcal: 131, protein: 5,   carbs: 25,  fat: 1.1 }, // per 100g
  tomato:      { kcal: 22,  protein: 1.1, carbs: 4.8, fat: 0.2 },
  basil:       { kcal: 2,   protein: 0.3, carbs: 0.3, fat: 0 },
  chicken:     { kcal: 165, protein: 31,  carbs: 0,   fat: 3.6 }, // per 100g
  "bell pepper":{kcal: 24,  protein: 1,   carbs: 6,   fat: 0.3 },
  ginger:      { kcal: 5,   protein: 0.1, carbs: 1.1, fat: 0 },
  chickpeas:   { kcal: 164, protein: 9,   carbs: 27,  fat: 2.6 }, // per 100g
  "curry powder":{kcal: 7,  protein: 0.3, carbs: 1.2, fat: 0.3 },
  "coconut milk":{kcal: 230,protein: 2,   carbs: 6,   fat: 24 }, // per 100g, rough
  lettuce:     { kcal: 15,  protein: 1.4, carbs: 2.9, fat: 0.2 },
  parmesan:    { kcal: 110, protein: 10,  carbs: 1,   fat: 7 },
  croutons:    { kcal: 30,  protein: 1,   carbs: 5,   fat: 1 },
  lemon:       { kcal: 17,  protein: 0.6, carbs: 5.4, fat: 0.2 },
  anchovy:     { kcal: 8,   protein: 1.3, carbs: 0,   fat: 0.4 },
  mushroom:    { kcal: 22,  protein: 3.1, carbs: 3.3, fat: 0.3 },
  "vegetable broth":{kcal:12,protein: 0.5,carbs: 2,  fat: 0.3 },
  "black beans":{kcal: 132, protein: 8.9, carbs: 24,  fat: 0.5 },
  tortilla:    { kcal: 90,  protein: 2.5, carbs: 15,  fat: 2 },
  cumin:       { kcal: 8,   protein: 0.4, carbs: 0.9, fat: 0.5 },
  lime:        { kcal: 20,  protein: 0.5, carbs: 7,   fat: 0.1 },
  cilantro:    { kcal: 1,   protein: 0.1, carbs: 0.1, fat: 0 },
  banana:      { kcal: 105, protein: 1.3, carbs: 27,  fat: 0.4 },
  flour:       { kcal: 364, protein: 10,  carbs: 76,  fat: 1 }, // per 100g
  milk:        { kcal: 103, protein: 8,   carbs: 12,  fat: 2.4 },
  sugar:       { kcal: 48,  protein: 0,   carbs: 12,  fat: 0 },
  lentils:     { kcal: 116, protein: 9,   carbs: 20,  fat: 0.4 },
  carrot:      { kcal: 25,  protein: 0.6, carbs: 6,   fat: 0.1 },
  celery:      { kcal: 10,  protein: 0.4, carbs: 2,   fat: 0.1 },
  bread:       { kcal: 80,  protein: 3,   carbs: 14,  fat: 1 },
  cheddar:     { kcal: 113, protein: 7,   carbs: 0.4, fat: 9 },
  paprika:     { kcal: 6,   protein: 0.3, carbs: 1.2, fat: 0.3 },
};
